name: tracker-gpu

dependencies:
  - python==3.7
  - pip
  - matplotlib
  - cudnn
  - cudatoolkit==10.1.243
  
  - pip:
    - nvidia-cuda-runtime-cu12
    - tensorflow-gpu==2.1.0
    - tensorflow-estimator==2.1.0
    - numpy==1.19
    - opencv-python==4.1.1.26
    - lxml
    - tqdm
    - seaborn
    - pillow
    - protobuf==3.20.1


